//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasraEmas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Member_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ICNo { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual EmasOwner EmasOwner { get; set; }
    }
}
