//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasraEmas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Month_year { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Target { get; set; }
        public int ID { get; set; }
    
        public virtual EmasOwner EmasOwner { get; set; }
    }
}
