//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasraEmas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Vehicle_ID { get; set; }
        public string Type { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public string PlateNo { get; set; }
        public string Color { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual EmasOwner EmasOwner { get; set; }
    }
}
